http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  front:
    host: localhost
    paths: ['/front','/front/*']
serviceEndpoints:
  front:
    url: 'http://loadbalancer/front/'
pipelines:
  default:
    apiEndpoints:
      - front
    policies:
      - proxy:
          - action:
              serviceEndpoint: front
              changeOrigin: true
              prependPath:  false
              ignorePath:   false
              stripPath:    false